options:
  apt-repo-spec:
    type: string
    default: "deb http://archive.admin.canonical.com/ubuntu precise-cat main"
    description: "Apt repository to install userdir-ldap from."
  apt-repo-keys:
    type: string
    default: null
    description: "Apt repository key, typically needed for apt-repo-spec."
  root-id-rsa:
    type: string
    default: null
    description: "An openssh-format RSA private key with no passphrase.  (This option is a trapdoor; setting it back to null has no real effect.)"
  template-hostname:
    type: string
    default: null
    description: "If the files rsynced from sshdist don't match our hostname, create a symlink to bridge the gap from /var/lib/misc/thishost."
  userdb-host:
    type: string
    default: "userdb.internal"
    description: "Name of the userdb host"
  userdb-ip:
    type: string
    default: "91.189.90.139"
    description: "IP address of the userdb host"
  userdb-known-hosts:
    type: string
    description: "A (possibly multiple-line) string of known_hosts entries to seed the userdb trust during install.  If none specified, ssh-keyscan will be used."
  users-to-migrate:
    type: string
    default: "ubuntu"
    description: "A space-separated list of usernames whose authorized_keys files should be migrated from ~/.ssh/authorized_keys to /etc/ssh/user-authorized-keys on install."
  domain:
    type: string
    description: "Fallback domain when none present. This is mostly to work around MAAS's failure to add DNS for LXC containers - LP#1274947."
