options:
  apt-repo-spec:
    type: string
    default: "deb http://archive.admin.canonical.com/ubuntu precise-cat main"
    description: "Apt repository to install userdir-ldap from."
  apt-repo-keys:
    type: string
    default: null
    description: "Apt repository key, typically needed for apt-repo-spec."
  userdb-host:
    type: string
    default: "userdb.internal"
    description: "Name of the userdb host"
  userdb-ip:
    type: string
    default: "91.189.90.139"
    description: "IP address of the userdb host"
  users-to-migrate:
    type: string
    default: "ubuntu"
    description: "A space-separated list of usernames whose authorized_keys files should be migrated from ~/.ssh/authorized_keys to /etc/ssh/user-authorized-keys on install."
  domain:
    type: string
    default: ""
    description: "Domain for which hosts are in"
