options:
  apt-repo-spec:
    type: string
    default: "deb http://archive.admin.canonical.com/ubuntu precise-cat main"
    description: >
        Apt repository to install userdir-ldap from.
  apt-repo-keys:
    type: string
    default: null
    description: >
        Apt repository key, typically needed for apt-repo-spec.
